version: "3"

services:
  database:
    image: postgres:14.1-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./backend/database_migrations:/docker-entrypoint-initdb.d
    networks:
      - backend-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
